
version: '2'

services:
  cmask-data-task:
    image: 'terrabrasilis/deter-cmask-data-task:v1.0.0'
    container_name: cmask-data-task
    restart: always
    environment:
      - "FORCE_YEAR_MONTH=2023-05-01"
      - "EVERY_DAY=yes"
    volumes:
      - '/dockerdata/deter-cmask-data-task/data:/usr/local/data'
    networks:
      - workspace-docker_default

networks:
  workspace-docker_default:
    external: true